services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: servicedb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  nats:
    image: nats:2.10-alpine
    command: "-js"
    restart: always
    ports:
      - "4222:4222"
      - "8222:8222"

  service-mqtt:
    build: .
    restart: on-failure
    depends_on:
      - postgres
      - nats
    environment:
      DATABASE_DSN: "postgres://user:password@postgres:5432/servicedb?sslmode=disable"
      NATS_URL: "nats://nats:4222"
      LISTEN_ADDR: ":9091"
    ports:
      - "9091:9091"
      - "1883:1883"

volumes:
  postgres-data: